### ISSUE TITLE
UTF-8 characters are not imported correctly in Bitwig

### ISSUE THREAD

**Issue by git-moss** [bitwig/dawproject#10]
Only tested with track names. E.g. name a track "äöüß". Import reads "Ã¤Ã¶ Ã¼ÃŸ".

**Comment by kurasu** [comment]
This must be an issue inside dawproject itself as we're just consuming the DOM, so it's probably lost in xml (de)-serialization. Let's add a test for this.

**Comment by git-moss** [comment]
Ah, right, you are using InputStreamReaders without specifying the character set in both load methods.
