### ISSUE TITLE
Nothing happens on project export

### ISSUE THREAD

**Issue by Jurek-Raben** [bitwig/dawproject#12]
Hi,
with beta 5, nothing happens here on "project export", no file will be created. macos 10.14.6 here

**Comment by git-moss** [comment]
Works for me (Windows 10).

**Comment by Jurek-Raben** [comment]
Hm still nothing happens with Beta6 macos mojave, JFYI

**Comment by git-moss** [comment]
Duplicate of #24

**Comment by kurasu** [comment]
problem was that it would only export if the .dawproject file extension was present, and the macOS dialog doesn't add that the same way as the windows one.
