### ISSUE TITLE
MIDI modulation envelopes ("points") are not imported

### ISSUE THREAD

**Issue by git-moss** [bitwig/dawproject#17]
1) Create some MIDI lanes (e.g. CC1, Aftertouch, Pitchbend) on a track in the arranger
2) Export it as dawproject -> points structures are present in the file
3) Import the dawproject file -> MIDI lanes are missing in the project

**Comment by git-moss** [comment]
Still in Bitwig 4.2 Beta 1

**Comment by kurasu** [comment]
I think this works now, attach an example project if there's still an issue.

**Comment by jorisroling** [comment]
You mean in the just released Bitwig v5?

**Comment by kurasu** [comment]
Well yes.. If you still think there's an issue please add an example dawproject file and your expected result.
