### ISSUE TITLE
VST3 parameter automation cannot be opened

### ISSUE THREAD

**Issue by git-moss** [bitwig/dawproject#21]
I automated the Cutoff parameter of u-he Repro-1, exported and reimported it:

![grafik](https://user-images.githubusercontent.com/3090132/128936910-ef7baaaa-1cd1-4744-9769-ae88c46a8309.png)

In Reaper I find values like "0:48" or "248:248". In dawproject only the second number is stored (parameterID="48").

**Comment by kurasu** [comment]
fixed for the next release™
