### ISSUE TITLE
Export dawproject is a noop (NixOS)

### ISSUE THREAD

**Issue by locallycompact** [bitwig/dawproject#24]
Hi, I have the menu item enabled using the config option, but exporting to dawproject just returns with no feedback or file produced, and no feedback to the spawning terminal. Behaviour is the same using the nix installed version and using the flatpak version.

**Comment by Jurek-Raben** [comment]
same here

**Comment by Jurek-Raben** [comment]
Habe ich jetzt gerade nochmal in Bitwog 4.1.2 getestet. Es wird immer noch nichts exportiert. Ich würde das Format gern in Renoise integrieren, aber wenn es nicht geht, dann ist das nur schwer zu realisieren...

**Comment by kurasu** [comment]
Should be fixed for 4.1.3. In current versions it should be possible to export if you add the .dawproject extension manually
