### ISSUE TITLE
Export to dawproject still a noop on 4.1.6

### ISSUE THREAD

**Issue by locallycompact** [bitwig/dawproject#29]
Hi, the Export Project button exists, the format drop down reads "DAW-project exchange format", but does not export.

**Comment by Tomczik76** [comment]
Also, is it possible to open a `.dawproject` file in Bitwig?

**Comment by locallycompact** [comment]
I don't have an example to try.

**Comment by Tomczik76** [comment]
I tried opening the `test.dawproject` file that gets created from the tests in Bitwig 4.1.6 and Bitwig crashes.

**Comment by kurasu** [comment]
this has been fixed for 4.2 Beta 3 (not available yet)

**Comment by kurasu** [comment]
make that beta 4
