### ISSUE TITLE
Future strategy for other programming languages

### ISSUE THREAD

**Issue by Trinitou** [bitwig/dawproject#39]
Hi, I really like the idea of the dawproject project and hope it gets adopted by more daws! :)

But I asked myself what the future strategy is for integrating the format into programs which use other programming languages? Maybe you can answer this, @kurasu ?

I mean maybe there is some C/C++ library being developed in the background which just isn't made public yet? Or is that up to volunteers to create a pull request? If so what would be the desired/most universal approach (e.g. to make it easy to create bindings for different languages)?

**Comment by kurasu** [comment]
There's no current plan on a C/C++ library from us, but anyone who would want to export the DOM to other languages could probably piggyback on the approach now used to generate the XML documentation. I might consider adding an example to generate the classes in swift or some other simple language which have a common XML parser (and String class) but I would have to deal with the hassle of doing that for C++ as I don't have any use for it myself.
