### ISSUE TITLE
What is currently supported here, and better example...

### ISSUE THREAD

**Issue by Jurek-Raben** [bitwig/dawproject#41]
Hi,

does Bitwig currently supports import of plugin states thru daw project? I am interested to build an export in Renoise, so it would ideally export note data, automation, all vst2/vst3 plugins and its states, and the routing of the plugins. Then what about group tracks?

Is there any working example which includes all the teasered features?

Thanks

**Comment by kurasu** [comment]
There is no real example project yet, you can create one by exporting from Bitwig Studio, but most features that are exposed should be functional at this stage, albeit with a few bugs in places. So audio events, warping, notes, automation, CCs, note-expression, track grouping, mixer settings & routing, plug-in states & automation should work in general.
