### ISSUE TITLE
Feature request: external samples

### ISSUE THREAD

**Issue by jneen** [bitwig/dawproject#72]
Hi there!

This is a super cool project, which I am using to help organize the mastering process of massive collabs. To that end, I find myself needing to generate projects with clips laid out in a specific way, and one kind of painful step that I'm running into is the need to copy every track (approx. 4 hours of audio over 75 files) into the zip container before I can open it with Bitwig.

Is there a way to reference external files and/or import an xml-only dawproject?

Thanks!
jneen

**Comment by jneen** [comment]
I'm also finding the need to programmatically read data about the project, which I used to do with Ableton's save files - It would be nice to be able to just export the project.xml without having to once again copy 4 hours of audio into a zip container.

**Comment by git-moss** [comment]
The file reference has an attribute "external". Set it to true to have the file out of the ZIP.

**Comment by jneen** [comment]
Oh! That's a really neat feature that I must have missed.
