### ISSUE TITLE
Difference between track.solo and mute

### ISSUE THREAD

**Issue by git-moss** [bitwig/dawproject#8]
Is there a reason why mute is defined differently than solo?

   @XmlElement(required = false)
   public BoolParameter mute;

   @XmlAttribute(required = false)
   public Boolean solo;

**Comment by git-moss** [comment]
Also Solo is not imported in Bitwig.

**Comment by kurasu** [comment]
The reason is that solo is not usually something you can automate.. We could of course still make it a BoolParameter, which might indeed be a better idea since it's conceivable that some DAW could automate it or that its used by other features (mapping, etc).

**Comment by git-moss** [comment]
Solo is neither imported nor exported in Bitwig 4.0.1 (also on master track).

**Comment by kurasu** [comment]
fixed in future version™
